name: Run all tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install gtest
      run: |
        sudo apt install libgtest-dev
        sudo apt-get install cmake
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp *.a /usr/lib
    - name: Build
      run: make test
    - name: Run
      run: for i in bin/*_test; do $i; done
